from __future__ import annotations

from typing import Protocol

from app.domain.models import Bookmaker, CanonicalEvent, PredictionMarketQuote, SportsbookQuote


class PredictionMarketAdapter(Protocol):
    async def list_events(self) -> list[CanonicalEvent]: ...
    async def list_markets(self) -> list[PredictionMarketQuote]: ...
    async def get_market(self, market_id: str) -> PredictionMarketQuote: ...
    async def get_order_book(self, market_id: str) -> PredictionMarketQuote: ...
    async def get_quotes(self) -> list[PredictionMarketQuote]: ...


class SportsbookOddsAdapter(Protocol):
    async def list_sports(self) -> list[str]: ...
    async def list_competitions(self) -> list[str]: ...
    async def list_events(self) -> list[CanonicalEvent]: ...
    async def list_bookmakers(self) -> list[Bookmaker]: ...
    async def get_event_odds(self, event_id: str) -> list[SportsbookQuote]: ...
